In [1]:
import pandas as pd

In [2]:
india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80,60,78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [3]:
us =  pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68,65,75]
})
us

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [5]:
df = pd.concat([india_weather, us])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [6]:
df = pd.concat([india_weather, us], keys = ["india", "us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [7]:
df.loc["india"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [8]:
temp = pd.DataFrame({
    "city": ["dehli","mumbai","banglore"],
    "temperature": [32,45,30],
})
temp

       city  temperature
0     dehli           32
1    mumbai           45
2  banglore           30

In [10]:
windspeed = pd.DataFrame({
    "city": ["dehli","mumbai"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed

     city  windspeed
1   dehli          7
0  mumbai         12

In [11]:
pd.concat([temp,windspeed],axis=1)

       city  temperature    city  windspeed
0     dehli           32  mumbai       12.0
1    mumbai           45   dehli        7.0
2  banglore           30     NaN        NaN

In [19]:
df2 =  pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [65,68,71],
})
df2

        city  temperature
0    chicago           65
1   new york           68
2  san diego           71

In [18]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando","baltimore"],
    "humidity": [21,14,35, 38]
})
df1

        city  humidity
0   new york        21
1    chicago        14
2    orlando        35
3  baltimore        38

In [17]:
df3 = pd.merge(df1, df2, on="city")
df3

Empty DataFrame
Columns: [city, humidity, temperature]
Index: []

In [20]:
df3 = pd.merge(df1, df2, on="city")
df3

       city  humidity  temperature
0  new york        21           68
1   chicago        14           65

In [21]:
df3 = pd.merge(df1, df2, on="city", how="inner")
df3

       city  humidity  temperature
0  new york        21           68
1   chicago        14           65

In [22]:
df3 = pd.merge(df1, df2, on="city", how="outer")
df3

        city  humidity  temperature
0  baltimore      38.0          NaN
1    chicago      14.0         65.0
2   new york      21.0         68.0
3    orlando      35.0          NaN
4  san diego       NaN         71.0

In [23]:
df3 = pd.merge(df1, df2, on="city", how="left")
df3

        city  humidity  temperature
0   new york        21         68.0
1    chicago        14         65.0
2    orlando        35          NaN
3  baltimore        38          NaN

In [24]:
df3 = pd.merge(df1, df2, on="city", how="right")
df3

        city  humidity  temperature
0    chicago      14.0           65
1   new york      21.0           68
2  san diego       NaN           71