In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather_by_cities.csv")
df

           day      city  temperature  windspeed   event
0   01-01-2017  new york           32          7    Rain
1   01-02-2017  new york           36          7   Sunny
2   01-03-2017  new york           28         12    Snow
3   01-04-2017  new york           33          7   Sunny
4   01-01-2017    mumbai           90          5   Sunny
5   01-02-2017    mumbai           85         12     Fog
6   01-03-2017    mumbai           87         15     Fog
7   01-04-2017    mumbai           92          5    Rain
8   01-01-2017     paris           45         20   Sunny
9   01-02-2017     paris           50         13  Cloudy
10  01-03-2017     paris           54          8  Cloudy
11  01-04-2017     paris           42         10  Cloudy

In [3]:
df[df.city=="new york"]

          day      city  temperature  windspeed  event
0  01-01-2017  new york           32          7   Rain
1  01-02-2017  new york           36          7  Sunny
2  01-03-2017  new york           28         12   Snow
3  01-04-2017  new york           33          7  Sunny

In [5]:
df[df.city=="new york"].temperature.max()

36

In [6]:
df.groupby("city")

In [10]:
g = df.groupby("city")

In [11]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data",data)

city: mumbai


data           day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
7  01-04-2017  mumbai           92          5   Rain
city: new york


data           day      city  temperature  windspeed  event
0  01-01-2017  new york           32          7   Rain
1  01-02-2017  new york           36          7  Sunny
2  01-03-2017  new york           28         12   Snow
3  01-04-2017  new york           33          7  Sunny
city: paris


data            day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [12]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data",data.temperature.max())

city: mumbai


data 92
city: new york


data 36
city: paris


data 54

In [13]:
g.get_group("paris")

           day   city  temperature  windspeed   event
8   01-01-2017  paris           45         20   Sunny
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
11  01-04-2017  paris           42         10  Cloudy

In [14]:
g.max()

                 day  temperature  windspeed  event
city
mumbai    01-04-2017           92         15  Sunny
new york  01-04-2017           36         12  Sunny
paris     01-04-2017           54         20  Sunny

In [16]:
g.min()

                 day  temperature  windspeed   event
city
mumbai    01-01-2017           85          5     Fog
new york  01-01-2017           28          7    Rain
paris     01-01-2017           42          8  Cloudy

In [21]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min  25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.0   8.5  12.75  15.0
new york       4.0   8.25  2.500000  7.0  7.0   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.5  11.5  14.75  20.0

In [23]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [32]:
def grouper(df, idx, col):
    if 80 <= df[col].loc[idx] <=90:
        return '80-90'
    elif 50 <= df[col].loc[idx] <= 60:
        return '50-60'
    else:
        return 'others'

In [33]:
g = df.groupby(lambda idx: grouper(df, idx, 'temperature'))
g

In [34]:
for key, d in g:
    print("key:", key)
    print("data:",d)

key: 50-60
data:            day   city  temperature  windspeed   event
9   01-02-2017  paris           50         13  Cloudy
10  01-03-2017  paris           54          8  Cloudy
key: 80-90
data:           day    city  temperature  windspeed  event
4  01-01-2017  mumbai           90          5  Sunny
5  01-02-2017  mumbai           85         12    Fog
6  01-03-2017  mumbai           87         15    Fog
key: others
data:            day      city  temperature  windspeed   event
0   01-01-2017  new york           32          7    Rain
1   01-02-2017  new york           36          7   Sunny
2   01-03-2017  new york           28         12    Snow
3   01-04-2017  new york           33          7   Sunny
7   01-04-2017    mumbai           92          5    Rain
8   01-01-2017     paris           45         20   Sunny
11  01-04-2017     paris           42         10  Cloudy