In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017       -99999          7     Sunny
2  01-03-2017           28     -99999      Snow
3  01-04-2017       -99999          7  no event
4  01-05-2017           32     -99999      Rain
5  01-06-2017           31          2     Sunny
6  01-07-2017           34     -88888  no event

In [4]:
df.replace(-99999, 0)

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017            0          7     Sunny
2  01-03-2017           28          0      Snow
3  01-04-2017            0          7  no event
4  01-05-2017           32          0      Rain
5  01-06-2017           31          2     Sunny
6  01-07-2017           34     -88888  no event

In [9]:
import numpy as np

df.replace([-99999,-88888], np.nan)

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  01-02-2017          NaN        7.0     Sunny
2  01-03-2017         28.0        NaN      Snow
3  01-04-2017          NaN        7.0  no event
4  01-05-2017         32.0        NaN      Rain
5  01-06-2017         31.0        2.0     Sunny
6  01-07-2017         34.0        NaN  no event

In [12]:
df.replace(to_replace=[-99999,-88888], value=np.nan)

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  01-02-2017          NaN        7.0     Sunny
2  01-03-2017         28.0        NaN      Snow
3  01-04-2017          NaN        7.0  no event
4  01-05-2017         32.0        NaN      Rain
5  01-06-2017         31.0        2.0     Sunny
6  01-07-2017         34.0        NaN  no event

In [13]:
df

          day  temperature  windspeed     event
0  01-01-2017           32          6      Rain
1  01-02-2017       -99999          7     Sunny
2  01-03-2017           28     -99999      Snow
3  01-04-2017       -99999          7  no event
4  01-05-2017           32     -99999      Rain
5  01-06-2017           31          2     Sunny
6  01-07-2017           34     -88888  no event

In [15]:
df.replace({
    'temperature' : -99999,
    'windspeed': [-99999, -88888],
    'event':'no event'
}, np.nan)

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0    NaN
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-07-2017         34.0        NaN    NaN

In [16]:
df.replace({
    -99999: np.nan,
    -88888: np.nan,
    'no event': 'sunny'
})

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0  sunny
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-07-2017         34.0        NaN  sunny

In [19]:
df = pd.DataFrame({
    'score' : ['exceptional','average','good','poor','average','exceptional'],
    'student' : ['rob','maya','parthiv','tom','julian','erica']
})

df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [22]:
df.replace(['poor','average','good','exceptional'],[1,2,3,4])

C:\Users\chaud\AppData\Local\Temp\ipykernel_6732\2662941392.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor','average','good','exceptional'],[1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica