In [14]:
import pandas as pd

In [3]:
df = pd.read_csv("score.csv")
df

    rohit   match#1    9
0   mohit   match#2   56
1     bob   match#3   56
2   rohit   match#4  120
3   rohit   match#5  105
4     bob   match#6   78
5   rohit   match#7  140
6     bob   match#8   45
7   rohit   match#9  130
8   mohit  match#10  102
9     bob  match#11  120
10    bob  match#12    5
11  mohit  match#13   72
12    bob  match#14   67

In [5]:
df = pd.read_csv("score.csv", skiprows=1)
df

    mohit   match#2   56
0     bob   match#3   56
1   rohit   match#4  120
2   rohit   match#5  105
3     bob   match#6   78
4   rohit   match#7  140
5     bob   match#8   45
6   rohit   match#9  130
7   mohit  match#10  102
8     bob  match#11  120
9     bob  match#12    5
10  mohit  match#13   72
11    bob  match#14   67

In [7]:
df = pd.read_csv("score.csv",header=1)
df

    mohit   match#2   56
0     bob   match#3   56
1   rohit   match#4  120
2   rohit   match#5  105
3     bob   match#6   78
4   rohit   match#7  140
5     bob   match#8   45
6   rohit   match#9  130
7   mohit  match#10  102
8     bob  match#11  120
9     bob  match#12    5
10  mohit  match#13   72
11    bob  match#14   67

In [9]:
df = pd.read_csv("score.csv",header=1, names = ["mohit", "match#2","56")]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (2108805633.py, line 1)

In [12]:
df = pd.read_csv("score.csv",header=1,nrows=6)
df

   mohit  match#2   56
0    bob  match#3   56
1  rohit  match#4  120
2  rohit  match#5  105
3    bob  match#6   78
4  rohit  match#7  140
5    bob  match#8   45

In [ ]:
df = pd.read_csv("score.csv", header=1, na_values = ['not avaliable', =1, 'n.a.'])
df

In [ ]:
df["pe"] = df["price"]/df["eps"]
df

In [ ]:
df.to_csv("pe1.csv",index=False, header=False)
df

In [ ]:
df = pd.read_excel("movies.xlsx", "movies")
df_movies

In [ ]:
df = pd.read_excel("movies.xlsx", "movies")
df_movies.head(4)

In [ ]:
df.financials = pd.read_excel("movies.xlsx", "financials")
df_financials.head(5)

In [ ]:
def standerdize_currency(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials = pd.read_excel("movies.xlsx", "financials", converters = {
    'currency': standardize_currency
})
df_financials.head(5)

In [ ]:
df_merged = pd.merge(df_movies,df_fanancials, on="movies_id")
df.merged

In [ ]:
df_merged.to_excel("movies_merged.xlsx", sheet_name="merged", index=False)

In [15]:
df_stocks = pd.Dataframe({
    'tickers' : ['GOOGL','wmt','MSFT'],
    'price' : [845, 65, 64],
    'pe': [30,37, 4, 61, 2.12]
})
df_stocks

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
df_weather = pd.Dataframe({
    'day' : ['1/1/2017','1/2/2017','1/3/2017'],
    'temp' : [845, 65, 64],
    'event': [30,37, 4, 61, 2.12]
})

In [ ]:
with pd.ExcelWriter("stocks_weather.xlsx") as writer:
    df_stocks.to_excel(writer, sheet_name"stocks")
    df_weather.to_excel(writer, sheet_name"weather")